"""api keys + request logs

Revision ID: 4bb760a34147
Revises: ee06d6fc3d44
Create Date: 2025-11-12 19:47:02.320787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb760a34147'
down_revision: Union[str, Sequence[str], None] = 'ee06d6fc3d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_org_api_key_name')
    )
    op.create_index(op.f('ix_organization_api_keys_org_id'), 'organization_api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_api_keys_prefix'), 'organization_api_keys', ['prefix'], unique=True)
    op.create_table('api_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['organization_api_keys.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_call_logs_api_key_id_created_at', 'api_call_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_api_call_logs_created_at', 'api_call_logs', ['created_at'], unique=False)
    op.create_index('ix_api_call_logs_org_id_created_at', 'api_call_logs', ['org_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_call_logs_org_id_created_at', table_name='api_call_logs')
    op.drop_index('ix_api_call_logs_created_at', table_name='api_call_logs')
    op.drop_index('ix_api_call_logs_api_key_id_created_at', table_name='api_call_logs')
    op.drop_table('api_call_logs')
    op.drop_index(op.f('ix_organization_api_keys_prefix'), table_name='organization_api_keys')
    op.drop_index(op.f('ix_organization_api_keys_org_id'), table_name='organization_api_keys')
    op.drop_table('organization_api_keys')
    # ### end Alembic commands ###
