"""document per-page grouping

Revision ID: 676faa57469d
Revises: 4bb760a34147
Create Date: 2025-11-13 00:06:09.804670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676faa57469d'
down_revision: Union[str, Sequence[str], None] = '4bb760a34147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('page_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_documents_group_id'), 'documents', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_group_id'), table_name='documents')
    op.drop_column('documents', 'page_number')
    op.drop_column('documents', 'group_id')
    # ### end Alembic commands ###
