"""documents batching, ocr jobs enum, indexes

Revision ID: ee06d6fc3d44
Revises: 039d189fd2d1
Create Date: 2025-11-12 17:57:45.208206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee06d6fc3d44'
down_revision: Union[str, Sequence[str], None] = '039d189fd2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_batch_id'), 'documents', ['batch_id'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'document_batches', ['batch_id'], ['id'])
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_template_field_id'), 'extracted_fields', ['template_field_id'], unique=False)

    # Ensure PostgreSQL enum type exists before altering column
    status_enum = sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='ocr_job_status')
    status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'ocr_jobs',
        'status',
        existing_type=sa.VARCHAR(length=20),
        type_=status_enum,
        existing_nullable=False,
        postgresql_using='status::ocr_job_status',
    )
    op.alter_column('ocr_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_ocr_jobs_document_id'), 'ocr_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_org_id'), 'ocr_jobs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_jobs_org_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_document_id'), table_name='ocr_jobs')
    op.alter_column('ocr_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # Revert status column to VARCHAR and drop enum type
    status_enum = sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='ocr_job_status')
    op.alter_column(
        'ocr_jobs',
        'status',
        existing_type=status_enum,
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        postgresql_using='status::text',
    )
    status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_extracted_fields_template_field_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_batch_id'), table_name='documents')
    op.drop_column('documents', 'batch_id')
    op.drop_table('document_batches')
    # ### end Alembic commands ###
